### ISSUE TITLE
[General] Feedback

### ISSUE THREAD

**Issue by jikkujose** [aka8921/clones#1]
### Never mix case styles.

`clones-monoRepo` is a bad name. Consider one of the following: `clones`, `ui-clones`, `clones-mono-repo`, `clones-monorepo`

### Be aware of code quality across files, even Readme files.

- Use Markdown link references to move long urls to document footer.
- Try aligning table markup (there are plugins for text editors that does this). 
- Maintain Readme with as much care as you maintain your code files.

### Write good commit messages

- Go through [this guideline][gc-guideline] for good commit messages.
- You can avoid writing long paragraphs for each commit, but try to atleast stick with the rules for the first line

### File structure

- Maintain consistent file structure (I have done first one for you)

[gc-guideline]: https://chris.beams.io/posts/git-commit/

**Comment by vighneshwho** [comment]
Sure,

Heres the status


## Things I've done so far

- changed the name of the repo
- the readme was cleaned up by you already. did use the same conventions on the commits after that
- the file structure is being maintained

**Comment by vighneshwho** [comment]
I will write better and well structured commit messages from the next commit onwards

**Comment by jikkujose** [comment]
1. Relook the commit message
2. See if there is a folder you need to rename

**Comment by vighneshwho** [comment]
Okay

**Comment by vighneshwho** [comment]
I forgot to push the changes.

**Comment by vighneshwho** [comment]
In the most recent commit I wrote the commit message as " [ 03 - pay-pal ] Apply basic scaffolding "

This is how it should be right ? thought of giving the name of the project so that understanding the project on which the commit applies would be clear. Is that a good practice ?

**Comment by jikkujose** [comment]
## 1. Commit labelling: 

Yes, its great that you are labelling commits. But be consistent:

Instead of:

```
- [03 pay-pal ]complete the side-bar ui
- [03 pay-pal] implement the send-money-card …
- [ 03 - pay-pal ]Implement UI of side-nav-menus
- [ 03 - pay-pal ] Apply basic scaffolding
```

Consider:
```
- [03] Add sidebar
- [03] Add send money card
- [03] Add side nav
- [03] Use basic scaffolding
```

### Note:

1. Simple number labelling may be more readable & less noisy
2. Use capital verbs to start (In present tense, this is subjective but in general use the same tense always)
3. Try to reduce the character count while maintaining meaning
4. Following these rules may be harder initially, but it will become second nature once you get the practice
5. Strive for using perfect English: mind capitalisation, punctuation, spacing & readability. Also consider reading [The Day You Became A Better Writer][oww].
6. Think about commit messages as a short story that you can read in a single sitting to know how your code progressed

## 2. Maintaining code

1. Always push as soon as you commit

## 3. Misc

1. Try consistent versioning in demos

[oww]: https://dilbertblog.typepad.com/the_dilbert_blog/2007/06/the_day_you_bec.html

**Comment by vighneshwho** [comment]
okay. I will take more care while writing commit messages.

I have some doubts

- How should I give the version names before the whole layout is done? I am currently thinkng of naming it as v0.1, v0.2 etc..

**Comment by vighneshwho** [comment]
Edited the commit messages to be more readable and understandable

**Comment by jikkujose** [comment]
Versioning: [Semantic versioning][sv] is the industry standard. Its essential for managing dependencies among many other advantages and is especially relevant in a large project with many contributors.

Using Semantic Versioning here will be an overkill. You can keep progressively increasing the version with each deployments like so: v1, v1, v3 & so on.

Consistency: I was referring to be consistent about which indexing scheme you would use (either 0 based or 1 based). That is: will it be v0, v1, v2 or v1, v2, v3. Anything you choose, stick to it for all implementations.

[sv]: https://semver.org/

**Comment by vighneshwho** [comment]
Okay. Will do the 1 based versioning

**Comment by jikkujose** [comment]
Check file structure.

**Comment by vighneshwho** [comment]
Okay

**Comment by vighneshwho** [comment]
There is an additional covidDashboard folder there. I'll fix it 👍

**Comment by vighneshwho** [comment]
Fixed
