### ISSUE TITLE
[32] Unsplash

### ISSUE THREAD

**Issue by jikkujose** [aka8921/clones#2]
- [ ] Perhaps design a simple banner overlay to direct them back to your portfolio. (like [this](https://github.blog/2008-12-19-github-ribbons/))
- [ ] The layouting is very well done! But I would have hand picked much better photos to make the experience standout
- [ ] Check font weights in the nav bar
- [ ] Font family is wrong, if interested, spend time learning about Typography

**Comment by vighneshwho** [comment]
Thank You for the feedback. I'll resolve the issues
